# Generated by Django 5.0.6 on 2024-07-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkToShortLink',
            new_name='AliasLink',
        ),
    ]
